// Datos extraídos de las fichas de datos de seguridad (FDS) de la obra ISFV Ayora 1.
// Cada producto indica el PDF original: ante cualquier duda manda la FDS original.
// nivel: 0 = sin clasificación de peligro · 1 = atención (irritante/alérgeno/medio ambiente) · 2 = peligro (inflamable/tóxico/aspiración)

const T = {
  INT: { n: "Instituto Nacional de Toxicología (24 h)", t: "915620420", show: "91 562 04 20" },
  E112: { n: "Emergencias", t: "112", show: "112" },
};

// Primeros auxilios estándar de las FDS TotalEnergies (formato Reglamento 2020/878)
const AA_TOTAL = {
  ojos: "Enjuagar con mucha agua, abriendo los párpados. Quitar lentillas. Médico si hay irritación.",
  piel: "Lavar con agua y jabón. Quitar ropa y calzado contaminados. Médico si hay síntomas.",
  inhalacion: "Sacar al aire libre y mantener en reposo. Médico si hay síntomas.",
  ingestion: "Enjuagar la boca con agua. NO provocar el vómito salvo indicación médica. Médico si hay síntomas.",
};
const FUEGO_TOTAL = {
  usar: "Polvo químico seco, CO₂, agua pulverizada (niebla) o espuma.",
  no: "NO usar chorro de agua directo.",
  nota: "Aislar la zona y evacuar. Bomberos con equipo autónomo. Los envases pueden reventar con el calor.",
};
const DERRAME_ACEITE = "Cortar la fuga si es seguro. Absorber con arena, tierra o vermiculita y meter en un envase para residuos. Evitar que llegue a alcantarillas, suelo o cauces. Cuidado: el suelo queda muy resbaladizo.";
const PRESION = "Aceite a presión (fugas de manguera): puede inyectarse bajo la piel sin herida visible. Es una urgencia médica aunque no duela: hospital sin esperar síntomas.";

const PRODUCTOS = [
  {
    id: "azolla-eco2-68",
    nombre: "AZOLLA ECO2 68",
    fabricante: "TotalEnergies",
    tipo: "Aceite hidráulico",
    familia: "aceites",
    uso: "Circuitos hidráulicos de maquinaria (ISO VG 68, HM/HLP).",
    alias: ["azolla", "eco2", "eco 2", "hlp", "hlp 68", "hidraulico", "iso 68", "vg 68", "68", "089248"],
    nivel: 0,
    peligro: "No clasificado como peligroso (CLP).",
    h: [],
    palabra: null,
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "210 °C (vaso abierto)",
    fecha: "2023-01-30", version: "v2", sds: "089248",
    fds: "azolla-eco2-68-fds.pdf", tds: "azolla-eco2-68-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: PRESION,
  },
  {
    id: "azolla-zs",
    nombre: "AZOLLA ZS 32 / 46 / 68",
    fabricante: "TotalEnergies",
    tipo: "Aceite hidráulico",
    familia: "aceites",
    uso: "Aceite hidráulico antidesgaste de alto rendimiento (solo ficha técnica disponible).",
    alias: ["azolla", "zs", "hidraulico", "32", "46", "68", "vg 32", "vg 46", "vg 68"],
    nivel: 0,
    sinFDS: true,
    peligro: "SIN FICHA DE SEGURIDAD en obra: solo se tiene la ficha técnica. Pedir la FDS al proveedor.",
    h: [],
    fecha: null, version: "Solo TDS",
    fds: null, tds: "azolla-zs-tds.pdf",
    tel: [T.INT],
    auxilios: {
      ojos: "Sin FDS. Como norma general con aceites: enjuagar con abundante agua.",
      piel: "Sin FDS. Lavar con agua y jabón.",
      inhalacion: "Sin FDS. Aire libre y reposo.",
      ingestion: "Sin FDS. No provocar el vómito. Llamar al Instituto Nacional de Toxicología.",
    },
    fuego: null,
    derrame: "Sin FDS. Como norma general: absorber con material inerte y evitar alcantarillas.",
    nota: PRESION,
  },
  {
    id: "equivis-zs-46",
    nombre: "EQUIVIS ZS 46",
    fabricante: "TotalEnergies",
    tipo: "Aceite hidráulico",
    familia: "aceites",
    uso: "Hidráulico antidesgaste de alto índice de viscosidad, para maquinaria de obra a la intemperie (HVLP).",
    alias: ["equivis", "zs", "hvlp", "hidraulico", "iso 46", "vg 46", "46", "31509"],
    nivel: 0,
    peligro: "No clasificado como peligroso (CLP).",
    h: [],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "215 °C (vaso abierto)",
    fecha: "2022-09-27", version: "v2", sds: "31509",
    fds: "equivis-zs-46-fds.pdf", tds: "equivis-zs-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: PRESION,
  },
  {
    id: "equivis-zs-68",
    nombre: "EQUIVIS ZS 68",
    fabricante: "TotalEnergies",
    tipo: "Aceite hidráulico",
    familia: "aceites",
    uso: "Hidráulico antidesgaste de alto índice de viscosidad, para maquinaria de obra a la intemperie (HVLP).",
    alias: ["equivis", "zs", "hvlp", "hidraulico", "iso 68", "vg 68", "68", "31508"],
    nivel: 0,
    peligro: "No clasificado como peligroso (CLP).",
    h: [],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "220 °C (vaso abierto)",
    fecha: "2022-11-10", version: "v2", sds: "31508",
    fds: "equivis-zs-68-fds.pdf", tds: "equivis-zs-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: PRESION,
  },
  {
    id: "liebherr-hydraulic-plus",
    nombre: "LIEBHERR HYDRAULIC PLUS",
    fabricante: "Liebherr",
    tipo: "Aceite hidráulico",
    familia: "aceites",
    uso: "Aceite hidráulico para maquinaria Liebherr.",
    alias: ["liebherr", "libherr", "hydraulic", "hidraulico", "plus", "1800400"],
    nivel: 0,
    peligro: "No obligatorio identificar como peligroso (ficha de 2009, formato antiguo).",
    h: [],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "182 °C (DIN ISO 2592)",
    fecha: "2009-02-17", version: "MSDS 1800400", sds: "1800400",
    fds: "liebherr-hydraulic-plus-fds.pdf", tds: null,
    tel: [T.INT],
    auxilios: {
      ojos: "Aclarar con agua corriente varios minutos con el ojo abierto.",
      piel: "Lavar inmediatamente con agua y jabón y enjuagar bien.",
      inhalacion: "No se precisan medidas especiales.",
      ingestion: "Consultar inmediatamente al médico.",
    },
    fuego: {
      usar: "CO₂, arena, polvo extintor.",
      no: "NO usar agua (chorro).",
      nota: "Puede formar gases tóxicos al calentarse o arder. Aparato de respiración autónomo.",
    },
    derrame: DERRAME_ACEITE,
    nota: PRESION,
  },
  {
    id: "tranself-trj-75w80",
    nombre: "TRANSELF TRJ 75W80 W",
    fabricante: "TotalEnergies",
    tipo: "Aceite de transmisión",
    familia: "aceites",
    uso: "Fluido de transmisión (cajas de cambio).",
    alias: ["tranself", "tranself", "trj", "75w80", "75w-80", "transmision", "cambio", "caja", "32753", "archive"],
    nivel: 1,
    peligro: "Nocivo para los organismos acuáticos con efectos duraderos (H412). Contiene componentes con riesgo de aspiración (<10 %).",
    h: [["H412", "Nocivo para los organismos acuáticos, con efectos nocivos duraderos."]],
    cas: "Mezcla (no aplica)",
    un: "No regulado (ADR)",
    flash: ">200 °C (vaso abierto)",
    fecha: "2022-10-27", version: "FDS 32753", sds: "32753",
    fds: "tranself-trj-75w80-fds.pdf", tds: null,
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE + " Es dañino para el medio acuático: que NO llegue a cauces ni alcantarillas.",
    nota: "Producto ambientalmente dañino: recoger todo derrame y gestionar el residuo con gestor autorizado.",
  },
  {
    id: "transmission-gear-8-fe-75w80",
    nombre: "TRANSMISSION GEAR 8 FE 75W-80",
    fabricante: "Total",
    tipo: "Aceite de transmisión",
    familia: "aceites",
    uso: "Aceite para cajas de cambio mecánicas (API GL-4). Solo ficha técnica disponible.",
    alias: ["transmission", "gear", "gear 8", "8 fe", "fe", "75w80", "75w-80", "caja", "cambio", "transmision"],
    nivel: 0,
    sinFDS: true,
    peligro: "SIN FICHA DE SEGURIDAD en obra: solo se tiene la ficha técnica (2017). Pedir la FDS.",
    h: [],
    fecha: "2017-05", version: "Solo TDS",
    fds: null, tds: "transmission-gear-8-fe-75w80-tds.pdf",
    tel: [T.INT],
    auxilios: {
      ojos: "Sin FDS. Enjuagar con abundante agua.",
      piel: "Sin FDS. Lavar con agua y jabón.",
      inhalacion: "Sin FDS. Aire libre y reposo.",
      ingestion: "Sin FDS. No provocar el vómito. Llamar al Instituto Nacional de Toxicología.",
    },
    fuego: null,
    derrame: "Sin FDS. Absorber con material inerte y evitar alcantarillas.",
    nota: null,
  },
  {
    id: "transmission-axle-7-85w140",
    nombre: "TRANSMISSION AXLE 7 85W-140 (GL-5)",
    fabricante: "Total",
    tipo: "Aceite de ejes / diferenciales",
    familia: "aceites",
    uso: "Lubricante de engranajes extrema presión (ejes, reductores finales).",
    alias: ["axle", "axle 7", "85w140", "85w-140", "gl5", "gl-5", "eje", "ejes", "diferencial", "reductor", "083161"],
    nivel: 1,
    peligro: "Sin clasificación de peligro relevante. Contiene una amina que puede provocar reacción alérgica en la piel (EUH208).",
    h: [["EUH208", "Contiene amina C12-14-terc-alquil. Puede provocar una reacción alérgica."]],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: ">200 °C",
    fecha: "2018-09-21", version: "v3.01", sds: "083161",
    fds: "axle7-85w140-fds.pdf", tds: "axle7-85w140-tds.pdf",
    tel: [T.INT, { n: "Total España 24 h (ficha 2018)", t: "900181566", show: "900 181 566" }, { n: "Urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: {
      ojos: "Lavar de inmediato con mucha agua, quitar lentillas y seguir al menos 15 minutos con el ojo abierto.",
      piel: "Eliminar lavando con jabón y mucha agua; quitar ropa contaminada. Si es a alta presión: hospital inmediato.",
      inhalacion: "Aire libre y reposo. Si no respira, respiración artificial (con mascarilla de bolsillo).",
      ingestion: "Limpiar la boca con agua. NO provocar el vómito. Llamar a un médico o al Instituto Nacional de Toxicología.",
    },
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: PRESION,
  },
  {
    id: "fluidmatic-d3",
    nombre: "FLUIDMATIC D3",
    fabricante: "TotalEnergies",
    tipo: "Fluido transmisión automática / dirección",
    familia: "aceites",
    uso: "Transmisiones automáticas y direcciones asistidas (Dexron III, Allison C4, MB 236.9…).",
    alias: ["fluidmatic", "fluimatc", "d3", "dexron", "atf", "automatica", "direccion", "transmision", "090167"],
    nivel: 1,
    peligro: "Puede provocar una reacción alérgica en la piel (H317). Evitar contacto prolongado.",
    h: [["H317", "Puede provocar una reacción alérgica en la piel."]],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: ">198 °C",
    fecha: "2022-11-30", version: "FDS 090167", sds: "090167",
    fds: "fluidmatic-d3-fds.pdf", tds: "fluidmatic-d3-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: {
      ...AA_TOTAL,
      piel: "Lavar con agua y jabón. Quitar ropa y calzado contaminados. Si aparece erupción o irritación: médico.",
    },
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: "Sensibilizante cutáneo: usar guantes (nitrilo) y lavar la piel tras el contacto. Una vez sensibilizado, la alergia puede reaparecer con muy poca exposición.",
  },
  {
    id: "rubia-tir-7400",
    nombre: "RUBIA TIR 7400 15W-40",
    fabricante: "Total",
    tipo: "Aceite de motor diésel",
    familia: "aceites",
    uso: "Motores diésel de vehículos industriales y obra (ACEA E5/E7, API CI-4).",
    alias: ["rubia", "tir", "7400", "15w40", "15w-40", "motor", "e7", "30579"],
    nivel: 0,
    peligro: "No clasificado como peligroso (CLP).",
    h: [],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: ">220 °C (vaso abierto)",
    fecha: "2021-03-03", version: "v1", sds: "30579",
    fds: "rubia-tir-7400-fds.pdf", tds: "rubia-tir-7400-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: "Aceite de motor usado: contiene contaminantes (combustión); evitar contacto de la piel y gestionar como residuo peligroso.",
  },
  {
    id: "rubia-works-4000",
    nombre: "RUBIA WORKS 4000 15W-40",
    fabricante: "TotalEnergies",
    tipo: "Aceite de motor diésel",
    familia: "aceites",
    uso: "Motores diésel de maquinaria de obra, minería y canteras (ACEA E9/E7, API CK-4, bajo SAPS).",
    alias: ["rubia", "works", "4000", "15w40", "15w-40", "motor", "088493", "low saps"],
    nivel: 0,
    peligro: "No clasificado como peligroso (CLP). Riesgo de resbalar sobre el derrame.",
    h: [],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "Ver FDS",
    fecha: "2023-01-04", version: "v2", sds: "088493",
    fds: "rubia-works-4000-fds.pdf", tds: "rubia-works-4000-tds.pdf",
    tel: [T.INT, { n: "TotalEnergies urgencias (internac.)", t: "+441235239670", show: "+44 1235 239670" }],
    auxilios: AA_TOTAL,
    fuego: FUEGO_TOTAL,
    derrame: DERRAME_ACEITE,
    nota: "Contacto repetido con la piel: sequedad, irritación y agrietamiento.",
  },
  {
    id: "multis-complex-ep2",
    nombre: "MULTIS COMPLEX EP 2",
    fabricante: "TotalEnergies",
    tipo: "Grasa",
    familia: "grasas",
    uso: "Grasa multipropósito de complejo de litio, extrema presión, alta temperatura (rodamientos, chasis, juntas).",
    alias: ["multis", "complex", "ep2", "ep 2", "grasa", "litio", "rodamientos", "engrase", "30935"],
    nivel: 0,
    sinFDS: true,
    peligro: "FDS ILEGIBLE: el PDF de la ficha de seguridad está corrupto. Solo hay ficha técnica. Volver a pedir/enviar la FDS.",
    h: [],
    fecha: "2022-06-30", version: "FDS 30935 (PDF dañado)",
    fds: null, tds: "multis-complex-ep2-tds.pdf",
    tel: [T.INT],
    auxilios: {
      ojos: "Sin FDS legible. Enjuagar con abundante agua.",
      piel: "Sin FDS legible. Lavar con agua y jabón.",
      inhalacion: "Sin FDS legible. Aire libre.",
      ingestion: "Sin FDS legible. No provocar el vómito. Llamar al Instituto Nacional de Toxicología.",
    },
    fuego: null,
    derrame: "Sin FDS legible. Recoger mecánicamente y gestionar como residuo.",
    nota: null,
  },
  {
    id: "tecnodiesel-e10",
    nombre: "TECNODIESEL e+10 (gasóleo A)",
    fabricante: "Repsol",
    tipo: "Combustible",
    familia: "combustibles",
    uso: "Gasóleo de automoción (maquinaria y vehículos).",
    alias: ["tecnodiesel", "diesel", "gasoleo", "gasoil", "gas oil", "e10", "e+10", "combustible", "repsol", "un1202", "1202", "68334-30-5", "gasoleo a"],
    nivel: 2,
    peligro: "Líquido inflamable. Puede ser MORTAL si se ingiere y entra en pulmones (aspiración). Nocivo por inhalación. Irrita la piel. Se sospecha que provoca cáncer. Tóxico para el medio acuático.",
    h: [
      ["H226", "Líquidos y vapores inflamables."],
      ["H304", "Puede ser mortal en caso de ingestión y penetración en las vías respiratorias."],
      ["H315", "Provoca irritación cutánea."],
      ["H332", "Nocivo en caso de inhalación."],
      ["H351", "Se sospecha que provoca cáncer."],
      ["H373", "Puede provocar daños en órganos tras exposiciones prolongadas o repetidas."],
      ["H411", "Tóxico para los organismos acuáticos, con efectos nocivos duraderos."],
    ],
    palabra: "PELIGRO",
    cas: "68334-30-5",
    un: "UN 1202 · clase 3 · GE III",
    flash: "≥ 60 °C (ASTM D-93)",
    fecha: "2015-05-13", version: "Rev. 3.0", sds: "30/0461/1D",
    fds: "tecnodiesel-e10-fds-2015.pdf", tds: "tecnodiesel-e10-fds-2009.pdf", tdsNombre: "FDS antigua 2009 (obsoleta)",
    tel: [T.INT, T.E112],
    auxilios: {
      ojos: "Lavar con agua varios minutos, quitar lentillas. Médico si hay irritación, visión borrosa o hinchazón.",
      piel: "Quitar ropa y calzado contaminados. Lavar a fondo con agua y jabón. Médico si hay irritación que persiste.",
      inhalacion: "Sacar a un lugar ventilado y tranquilo. Si no respira: respiración artificial. Si respira: posición de recuperación. Médico si hay dificultad respiratoria.",
      ingestion: "URGENCIA: enviar al hospital inmediatamente. Suponer siempre que ha habido aspiración. NO provocar el vómito. No dar nada por la boca a un inconsciente.",
    },
    fuego: {
      usar: "Espuma, niebla de agua, polvo químico seco, CO₂, arena o tierra.",
      no: "NO chorro directo de agua sobre el producto ardiendo. No usar espuma y agua a la vez en la misma superficie.",
      nota: "Los vapores pueden llegar a un foco lejano y prender. Enfriar los envases expuestos a las llamas.",
    },
    derrame: "Eliminar focos de ignición. Contener y absorber con material inerte (arena, tierra). Impedir que llegue a alcantarillas o cauces. Informar a las autoridades si hay contaminación.",
    nota: "Nunca chupar/sifonar gasóleo con la boca ni usarlo para limpiarse las manos. Si se ingiere, NO provocar el vómito: el mayor riesgo es que pase al pulmón.",
  },
  {
    id: "gasoleo-diesel-e",
    nombre: "GASÓLEO DIESEL e+ (Repsol)",
    fabricante: "Repsol",
    tipo: "Combustible",
    familia: "combustibles",
    uso: "Gasóleo de automoción. Ficha antigua (2011).",
    alias: ["diesel e+", "diesel", "gasoleo", "gasoil", "gas oil", "combustible", "repsol", "un1202", "1202", "68334-30-5", "e+"],
    nivel: 2,
    peligro: "Nocivo por inhalación, irrita la piel, peligro de aspiración (puede ser mortal si pasa al pulmón), sospechoso de cáncer (cat. 3), nocivo para el medio acuático. Combustible.",
    h: [
      ["H226", "Líquidos y vapores inflamables."],
      ["H304", "Puede ser mortal en caso de ingestión y penetración en las vías respiratorias."],
      ["H315", "Provoca irritación cutánea."],
      ["H332", "Nocivo en caso de inhalación."],
      ["H351", "Se sospecha que provoca cáncer."],
      ["H373", "Puede provocar daños en órganos tras exposiciones prolongadas o repetidas."],
      ["H411", "Tóxico para los organismos acuáticos, con efectos nocivos duraderos."],
    ],
    cas: "68334-30-5",
    un: "UN 1202",
    flash: "Ver FDS",
    fecha: "2011-11-07", version: "Rev. 1.2", sds: "30/0463/1D.06",
    fds: "gasoleo-diesel-e-fds-2011.pdf", tds: null,
    tel: [T.INT, T.E112],
    auxilios: {
      ojos: "Lavar con agua abundante varios minutos. Médico si hay irritación.",
      piel: "Quitar ropa contaminada. Lavar con agua y jabón.",
      inhalacion: "Sacar al aire libre y reposo. Médico si hay síntomas.",
      ingestion: "NO provocar el vómito (riesgo de aspiración). Llevar a un hospital de inmediato.",
    },
    fuego: {
      usar: "Espuma, polvo químico seco, CO₂, niebla de agua.",
      no: "NO chorro directo de agua.",
      nota: "Puede arder por calor, chispas, electricidad estática o llamas. Los envases pueden explotar con el calor.",
    },
    derrame: "Eliminar focos de ignición. Absorber con arena o tierra. Impedir que llegue a alcantarillas o cauces.",
    nota: "Ficha de 2011: usar preferentemente la del TecnoDiesel e+10 (2015) o pedir la actual a Repsol (FDSRCPP@repsol.com).",
  },
  {
    id: "disolvente-nu20",
    nombre: "DISOLVENTE UNIVERSAL NU-20",
    fabricante: "Alcoholes del Sur",
    tipo: "Disolvente (tolueno)",
    familia: "pinturas",
    uso: "Disolvente / diluyente universal.",
    alias: ["disolvente", "nu20", "nu-20", "nu 20", "universal", "diluyente", "tolueno", "acetona", "thinner", "un1263", "1263", "alcoholes del sur", "108-88-3"],
    nivel: 2,
    peligro: "Líquido MUY inflamable. Puede ser mortal si se ingiere y entra en pulmones. Se sospecha que daña al feto. Daña órganos con exposición repetida (inhalación). Irrita piel y ojos. Somnolencia y vértigo.",
    h: [
      ["H225", "Líquido y vapores muy inflamables."],
      ["H304", "Puede ser mortal en caso de ingestión y penetración en las vías respiratorias."],
      ["H315", "Provoca irritación cutánea."],
      ["H319", "Provoca irritación ocular grave."],
      ["H336", "Puede provocar somnolencia o vértigo."],
      ["H361d", "Se sospecha que daña al feto."],
      ["H373", "Puede provocar daños en órganos tras exposiciones prolongadas o repetidas por inhalación."],
    ],
    palabra: "PELIGRO",
    cas: "Tolueno 108-88-3 (60-70 %), isopropanol, acetona, acetato de butilo",
    un: "UN 1263 · clase 3",
    flash: "-2 °C",
    fecha: "2018-02-05", version: "v37", sds: "v37",
    fds: "disolvente-nu20-fds.pdf", tds: null,
    tel: [T.INT, T.E112],
    auxilios: {
      ojos: "Quitar lentillas y lavar con abundante agua limpia al menos 10 minutos, abriendo los párpados. No frotar. Buscar asistencia médica.",
      piel: "Quitar la ropa contaminada. Lavar con agua y jabón. NUNCA usar disolventes ni diluyentes para limpiarse.",
      inhalacion: "Aire libre, caliente y en reposo. Si respira mal o no respira: respiración artificial. Si está inconsciente: posición adecuada y pedir ayuda médica.",
      ingestion: "Atención médica inmediata. Reposo. NUNCA provocar el vómito.",
    },
    fuego: {
      usar: "Polvo extintor o CO₂. En incendios mayores, espuma resistente al alcohol y agua pulverizada.",
      no: "NO chorro directo de agua. Con tensión eléctrica no usar agua ni espuma.",
      nota: "Producto fácilmente inflamable: puede agravar mucho un incendio.",
    },
    derrame: "Eliminar focos de ignición y ventilar. Absorber con material inerte no combustible. Evitar alcantarillas y cauces. Los vapores son más pesados que el aire.",
    nota: "Contiene tolueno (sospecha de daño al feto, H361d): trabajadoras embarazadas o en lactancia deben consultarlo con PRL / vigilancia de la salud antes de usarlo. No usar para limpiarse las manos. Trabajar solo con buena ventilación, sin chispas ni fumar.",
  },
  {
    id: "galvafix-zinc",
    nombre: "GALVAFIX ALTO CONTENIDO ZINC",
    fabricante: "Galvafix",
    tipo: "Pintura galvanizado en frío",
    familia: "pinturas",
    uso: "Pintura líquida con alto contenido de zinc para protección anticorrosión.",
    alias: ["galvafix", "galva", "zinc", "cinc", "galvanizado", "pintura", "333608", "un1263", "1263", "7440-66-6", "xileno"],
    nivel: 2,
    peligro: "Líquido y vapores inflamables. Irrita piel y ojos. Muy tóxico para los organismos acuáticos con efectos duraderos.",
    h: [
      ["H226", "Líquidos y vapores inflamables."],
      ["H315", "Provoca irritación cutánea."],
      ["H319", "Provoca irritación ocular grave."],
      ["H410", "Muy tóxico para los organismos acuáticos, con efectos duraderos."],
    ],
    palabra: "ATENCIÓN",
    cas: "Zinc 7440-66-6; xileno 1330-20-7",
    un: "UN 1263 PINTURA · clase 3 · GE III",
    flash: "26 °C",
    fecha: "2022-11-25", version: "v3", sds: "333608",
    fds: "galvafix-zinc-fds.pdf", tds: null,
    tel: [T.INT, { n: "Fabricante (9-14 h y 16-19 h)", t: "+34942580028", show: "+34 942 580 028" }],
    auxilios: {
      ojos: "Quitar lentillas. Lavar con abundante agua limpia al menos 15 minutos, abriendo los párpados. Asistencia médica inmediata.",
      piel: "Quitar la ropa contaminada. Lavar a fondo con agua fría o templada y jabón neutro.",
      inhalacion: "Sacar al aire libre. Si la respiración es irregular o se detiene, respiración artificial. Si está inconsciente, posición de recuperación y abrigado.",
      ingestion: "Asistencia médica inmediata. NO provocar el vómito (riesgo de aspiración). Reposo.",
    },
    fuego: {
      usar: "Polvo extintor o CO₂.",
      no: "—",
      nota: "Refrigerar con agua los envases cercanos al fuego. Evitar que el agua de extinción llegue a desagües.",
    },
    derrame: "Eliminar focos de ignición, ventilar, no fumar. Recoger con material absorbente no combustible (tierra, arena, vermiculita). Guardar en contenedor cerrado. Evitar desagües y cauces.",
    nota: "Trabajar con ventilación y sin fuentes de ignición. Muy tóxico para el agua: no lavar brochas ni envases en desagües.",
  },
  {
    id: "marker-paint",
    nombre: "CRC MARKER PAINT (aerosol fluorescente)",
    fabricante: "CRC",
    tipo: "Pintura en aerosol",
    familia: "pinturas",
    uso: "Aerosol de marcaje (colores fluorescentes: rojo, verde, amarillo, azul, naranja…).",
    alias: ["marker", "paint", "crc", "aerosol", "spray", "marcaje", "pintura", "fluorescente", "fluor", "un1950", "1950", "marcador", "replanteo"],
    nivel: 2,
    peligro: "Aerosol EXTREMADAMENTE inflamable. Recipiente a presión: puede reventar si se calienta. Irrita gravemente los ojos. Puede provocar somnolencia o vértigo.",
    h: [
      ["H222", "Aerosol extremadamente inflamable."],
      ["H229", "Recipiente a presión: puede reventar si se calienta."],
      ["H319", "Provoca irritación ocular grave."],
      ["H336", "Puede provocar somnolencia o vértigo."],
    ],
    palabra: "PELIGRO",
    cas: "Contiene acetato de n-butilo y acetato de etilo",
    un: "Aerosoles (UN 1950)",
    flash: "-57 °C (propelente)",
    fecha: "2017-06-29", version: "v3.0", sds: "BDS001592",
    fds: "marker-paint-fds.pdf", tds: null,
    tel: [T.INT, { n: "CRC Bélgica (horario oficina)", t: "+3252456011", show: "+32 52 45 60 11" }],
    auxilios: {
      ojos: "Aclarar cuidadosamente con agua varios minutos. Quitar lentillas si es fácil. Seguir aclarando. Médico si persiste.",
      piel: "Quitar ropa contaminada. Lavar con agua y jabón abundantes. Médico si hay irritación.",
      inhalacion: "Llevar al aire libre en posición que facilite la respiración. Llamar a toxicología o médico si hay malestar.",
      ingestion: "Si se aspira accidentalmente no provocar el vómito y avisar al médico.",
    },
    fuego: {
      usar: "Espuma, CO₂ o polvo.",
      no: "—",
      nota: "Los aerosoles pueden explotar por encima de 50 °C. Mantener fríos con agua los recipientes expuestos al fuego. No respirar los gases del incendio.",
    },
    derrame: "Apagar todas las fuentes de ignición y ventilar.",
    nota: "No dejar al sol ni en el coche/cabina (no superar 50 °C). No perforar ni quemar, ni vacío. No pulverizar cerca de llamas o chispas (radial, soldadura).",
  },
  {
    id: "sikafill-380-thermic",
    nombre: "SIKAFILL-380 THERMIC",
    fabricante: "Sika",
    tipo: "Revestimiento / impermeabilizante",
    familia: "pinturas",
    uso: "Revestimiento elástico acrílico con propiedades térmicas para cubiertas.",
    alias: ["sika", "sikafill", "380", "thermic", "impermeabilizante", "revestimiento", "cubierta", "acrilico", "bit"],
    nivel: 1,
    peligro: "No es mezcla peligrosa según CLP. Contiene biocidas (BIT, MIT): puede provocar reacción alérgica (EUH208). Al rociar pueden formarse gotas respirables: no respirar el aerosol (EUH211).",
    h: [
      ["EUH208", "Contiene BIT y mezcla C(M)IT/MIT. Puede provocar una reacción alérgica."],
      ["EUH211", "¡Atención! Al rociar pueden formarse gotas respirables peligrosas. No respirar el aerosol."],
    ],
    cas: "Mezcla (no aplica)",
    un: "No regulado",
    flash: "> 101 °C",
    fecha: "2023-10-06", version: "v7.0", sds: "100000010028",
    fds: "sikafill-380-thermic-fds.pdf", tds: null,
    tel: [T.INT, { n: "Sika España (7:30-18:00)", t: "+34916621818", show: "+34 91 662 18 18" }],
    auxilios: {
      ojos: "Quitar lentillas. Lavar con el ojo bien abierto.",
      piel: "Quitar ropa y zapatos contaminados. Lavar con jabón y mucha agua.",
      inhalacion: "Trasladar a un espacio abierto.",
      ingestion: "No provocar el vómito sin consejo médico. Enjuagar la boca con agua. No dar leche ni alcohol. Nada por la boca a un inconsciente.",
    },
    fuego: null,
    derrame: "Ver ficha original (sección 6).",
    nota: "Si se aplica por pulverización: mascarilla adecuada. Guantes para evitar sensibilización.",
  },
];

const GRUPOS = [
  { id: "todos", n: "Todos" },
  { id: "aceites", n: "Aceites" },
  { id: "grasas", n: "Grasas" },
  { id: "combustibles", n: "Combustibles" },
  { id: "pinturas", n: "Pinturas y disolventes" },
];
